baseurl: "/"
languageCode: "de-de"
title: "madcats[welt]"
metaDataFormat: "yaml"
theme: "mcw"
permalinks:
  post: /:year/:month/:title/
canonifyURLs: true
enableRobotsTXT: true
googleAnalytics: "UA-1711787-1"
staticDir: ["static"]
